version: '2.1'

parameters:
  deploy:
    type: boolean
    default: false

jobs:
  demo:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo << pipeline.git.branch >>
      - run: cat file.txt

workflows:
  setup:
    when: << pipeline.parameters.deploy >>
    jobs:
      - demo
