version: '2.1'

parameters:
  deploy:
    type: boolean
    default: false

jobs:
  demo-env:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: echo << pipeline.git.branch >>
      - run: echo << parameters.image_tag >>

workflows:
  setup:
    when: << pipeline.parameters. >>
    jobs:
      - demo
