version: '2.1'

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ./test.yml
      - continuation/continue:
          configuration_path: ./build.yml
